import { Nunito } from 'next/font/google'

import Navbar from './components/navbar/Navbar'
import LoginModal from './components/modals/LoginModal'
import RegisterModal from './components/modals/RegisterModal'
import SearchModal from './components/modals/SearchModal'
import RentModal from './components/modals/RentModal'

import ToasterProdiver from './providers/ToasterProdiver'

import './globals.css'
import Categories from './components/navbar/Categories'
import getCurrentUser from './actions/getCurrentUser'
import ClientOnly from './components/shared/ClientOnly'
import { SafeUser } from './types';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const font = Nunito({
	subsets: ['latin']
})

export default async function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	const currentUser = await getCurrentUser()

	return (
		<html lang='en'>
			<body className={font.className}>
				<ClientOnly>
					<ToasterProdiver />
					<LoginModal />
					<RegisterModal />
					<SearchModal />
					<RentModal />
					<Navbar currentUser={currentUser} />
					<Categories />
				</ClientOnly>
				<div className='pb-20 pt-28'>{children}</div>
			</body>
		</html>
	)
}
